services:
  # Backend API Service
  - type: web
    name: bookit-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString

  # PostgreSQL Database
databases:
  - name: bookit-db
    plan: free
    databaseName: bookit
    user: bookit

